### ISSUE TITLE
Tracking Image

### ISSUE THREAD

**Issue by ghost** [CrimsonForge-io/king-phisher#11]
Hello, 

How do I get the tracking image to work?  Do I just need to add {{ tracking_dot_image_tag }} to my html file?

**Comment by knc331** [comment]
I am also facing the same issue. The only thing that seems to be reporting are the emails that were sent. Check my HTML code below.

<html>
<a href="{{ url.webserver }}">
{{ inline_image('/root/Desktop/PhisihngMessage.png') }}

</a>

<br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    {{ tracking_dot_image_tag }}
</body>
</html>

**Comment by wolfthefallen** [comment]
The tracking dot will only work if you have a valid Web Server URL that points to your King Phisher Server. Make sure your Web Server URL is correct and your url.webserver link is working correctly and taking you to your landing page, and also being tracked by King Phisher.

**Comment by zeroSteiner** [comment]
@knc331 If you still have questions, please open a new ticket.

**Comment by knc331** [comment]
Can you please help me with the point highlighted by you "The tracking dot will only work if you have a valid Web Server URL that points to your King Phisher Server". Please share some links on that if any.

**Comment by knc331** [comment]
I need to run the apache server and as well to host the website or if i point the webroot to /var/www will be suffice ? Still tracking thing is not working on my system. Website and the KingPhisher server on the same machine. Please help.

**Comment by ogpadre** [comment]
> I need to run the apache server and as well to host the website or if i point the webroot to /var/www will be suffice ? Still tracking thing is not working on my system. Website and the KingPhisher server on the same machine. Please help.

I have the same question
Can you help me with this?

**Comment by ogpadre** [comment]
@knc331 @wolfthefallen 
Can you please help me to make the tracking dot working step by step?

**Comment by wolfthefallen** [comment]
@ogpadre KingPhisherServer is its own Web Server. if you are running apache, ngix or another webserver you will not be able to gather any information to track. You need to utilize KingPhishers webserver to track images, clicks, landings, username/password entries etc. 

Please Visit the [wiki ](https://github.com/rsmusllp/king-phisher/wiki )and watch the [How To Vidoes](https://github.com/securestate/king-phisher/wiki/Videos#how-to-videos) for additional information.
