### ISSUE TITLE
Client setup wont run

### ISSUE THREAD

**Issue by Marijnone** [CrimsonForge-io/king-phisher#2]
Hello,

I'm currently trying to get King-phisher to work on my Kali-linux machine, i did everything according to the install file and when i run ./KingPhisher i get prompted with the SSH login screen, then i start SSH service. but i don't have any right credentials to put in. and when i run the client-setup the terminal pops up for a second and then disappears.. then i tried kingphisher --help but im still stuck.. so i would really appreciate some help.

**Comment by debengils** [comment]
how to i got the password server login? please somebody can help?

**Comment by wolfthefallen** [comment]
@debengils The answer to your question is located in our [FAQ](https://github.com/securestate/king-phisher/wiki/Frequently-Asked-Questions). For your specific question please see [what is the default credentials](https://github.com/securestate/king-phisher/wiki/Frequently-Asked-Questions#what-are-the-default-credentials)

If you need any other or have issues please open a new ticket.

**Comment by debengils** [comment]
-- Unit user@117.service has finished shutting down.
Oct 24 02:38:37 dbn systemd[1]: Removed slice User Slice of postgres.
-- Subject: Unit user-117.slice has finished shutting down
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit user-117.slice has finished shutting down.
Oct 24 02:38:37 dbn python3[6729]: WARNING  the specified geoip database does not exist, downloading a new copy
Oct 24 02:39:01 dbn CRON[6789]: pam_unix(cron:session): session opened for user root by (uid=0)
Oct 24 02:39:01 dbn CRON[6790]: (root) CMD (  [ -x /usr/lib/php/sessionclean ] && if [ ! -d /run/systemd/system ]; then /usr/lib/php/sessionclea
Oct 24 02:39:01 dbn CRON[6789]: pam_unix(cron:session): session closed for user root
Oct 24 02:40:04 dbn systemd[1]: king-phisher.service: Start operation timed out. Terminating.
Oct 24 02:40:04 dbn systemd[1]: king-phisher.service: Failed with result 'timeout'.
Oct 24 02:40:04 dbn systemd[1]: Failed to start King Phisher Server.
-- Subject: Unit king-phisher.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit king-phisher.service has failed.
-- 
-- The result is RESULT.
